### ISSUE TITLE
Clean up cal files

### ISSUE THREAD

**Issue by DavidBrainard** [gkaguirrelab/OLApproach_Squint#5]
The calibration directory needs some attention.

a) There is one calibration file with apostrophes in its name.
b) There are two calibration files with _TMP in its name.
c) In oldCals, there is a calibration file with _wrong in its name

If any of these have a use, add a README file that explains what they are.  Otherwise, I think they should be deleted.

d) There are numerous calibration files without the '_' before the ND specification.  Please insert to match our convention, and name new ones with the '_'.  You'll need to change the places where these are called in the code to match. Should not be hard to find those, though.

e) There are a bunch of BoxB calibration files at the main level.  Did we ever use BoxB in an actual experiment here?  If not, move to oldCals.  I think I would also do that with the BoxA cals, and any BoxD cals that were never used in data collection.

**Comment by harrison-mcadams** [comment]
Cleaned up, with README added.
